steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/backend/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/${PROJECT_ID}/gamemod-api/backend:latest
      - .
images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/gamemod-api/backend:latest
